#!/bin/bash
#PBS -l walltime=10:00:00 
#PBS -N calculate_cells_per_sample
#PBS -m abe

#module load pandas
module load scikit-learn/1.1.2-foss-2022a
module load matplotlib/3.5.2-foss-2022a

python $VSC_HOME/final_thesis/preprocessing/real/cell_counts1.py --data_dir "$VSC_DATA_VO_USER/HDF5/WBC" 
#python VSC_HOME/Thesis/preprocessing/real/cell_counts.py --data_dir "$VSC_DATA_VO_USER/HDF5/WBC/" --cellnames_file "$VSC_HOME/final_thesis/wbc_cellnames.txt"